version: "3.9"

services:
  tf-api:
    tty: true
    container_name: tf-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - ENVIRONMENT_IP=localhost
      - SERVER_PORT=3000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
        condition: on-failure


