version: "3.9"

services:
  tf-api:
    container_name: tf-api
    image: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - ENVIRONMENT_IP=localhost
      - SERVER_PORT=3000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - tf-db
    deploy:
      restart_policy:
        condition: on-failure

  tf-db:
    container_name: tf-db
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  mongodata:
